project_name: git-sweep

version: 2

builds:
  - id: git-sweep
    main: ./cmd/git-sweep
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags: []

archives:
  - id: archives
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

dockers: []

dist: dist

changelog:
  use: git
